# Generated by Django 4.1.7 on 2023-06-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_producttype_slug_subcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='number_of_items',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
