# Generated by Django 3.2 on 2023-07-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230712_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img3',
            field=models.ImageField(upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img4',
            field=models.ImageField(upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img5',
            field=models.ImageField(upload_to='products'),
        ),
    ]
