# Generated by Django 4.1.7 on 2023-06-30 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id2', models.UUIDField(default=uuid.uuid1)),
                ('tracking_id3', models.UUIDField(default=uuid.UUID)),
                ('tracking_id4', models.UUIDField(default=uuid.uuid3)),
                ('tracking_id', models.UUIDField(default=uuid.uuid4)),
                ('tracking_id5', models.UUIDField(default=uuid.uuid5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
