# Generated by Django 4.1.7 on 2023-06-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_no_sold_review_date_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tracking_id3',
        ),
    ]
