# Generated by Django 3.2 on 2023-07-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230712_0222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('under review', 'Under Review'), ('approved', 'Approved'), ('declined', 'Declined')], default='under review', max_length=20),
        ),
    ]
