# Generated by Django 4.1.7 on 2023-06-30 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_order_tracking_id3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tracking_id4',
        ),
    ]
