# Generated by Django 3.2 on 2023-07-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='actual_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='no_sold',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
