# Generated by Django 4.1.7 on 2023-06-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_order_tracking_id4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tracking_id5',
        ),
    ]
