# Generated by Django 4.1.7 on 2023-07-01 07:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_order_tracking_id5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tracking_id2',
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
