# Generated by Django 3.2 on 2023-07-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_product_no_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('under review', 'Under Review'), ('approved', 'Approved'), ('declined', 'Declined')], default='under review', max_length=20),
        ),
    ]
