# Generated by Django 4.1.7 on 2023-07-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_order_options_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='badge',
            field=models.CharField(default='', max_length=30),
        ),
    ]
