# Generated by Django 4.1.7 on 2023-07-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_order_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='badge',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
