# Generated by Django 4.1.7 on 2023-07-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_order_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in progress', max_length=40),
        ),
    ]
