# Generated by Django 4.1.7 on 2023-07-21 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_cartitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart_Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_items", models.PositiveIntegerField(default=1)),
                ("session", models.CharField(max_length=255)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.product"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
