# Generated by Django 3.2 on 2023-07-22 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230721_2010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialLink',
        ),
        migrations.AlterField(
            model_name='billing',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
